# -*- coding: utf-8 -*-
"""Export_MobileNET_PI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8xk0wDIdAIzZ2Wj3x2xMLxahC_UX5nW

#Problem
We want to deploy the trained model on the Raspberry Pi for image classification
But this  models are too big and slow for this device.

**The goal is to make the model small and fast enough to run on the Raspberry Pi without losing accuracy.**

#Mounting the Drive
This step is necessary in Colab because it operates in a temporary virtual environment, meaning that files saved directly in the Colab VM are deleted once the session ends. This integration also provides easy access to shared folders or files in Google Drive, making collaboration more efficient.
"""

from google.colab import drive  # Import the drive module from Google Colab to access Google Drive
drive.mount('/content/drive')   # Mount Google Drive to the Colab environment at the specified path

"""#Exporting the model
Deploying machine learning models on devices like the Raspberry Pi has become increasingly popular for applications requiring low-latency and on-device processing.

However, traditional models are often too large and computationally intensive for resource-constrained hardware.

Using a lightweight, pre-trained MobileNet model with transfer learning in Keras and exporting it to TensorFlow Lite (TFLite) format creates an optimized, efficient model for real-time inference on the Raspberry Pi.

"""

import tensorflow as tf
from tensorflow import keras

model = keras.models.load_model('/content/drive/My Drive/Colab Notebooks/VET_Proje/models/atik_classifier_model_AUG_FV2.keras')


converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model
with open('/content/drive/My Drive/Colab Notebooks/VET_Proje/models/atik_classifier_model_AUG.tflite', 'wb') as f:
    f.write(tflite_model)